root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
env:
  es2021: true
parserOptions:
  project:
    - "./tsconfig.eslint.json"
  ecmaVersion: "latest"
rules:
  "@typescript-eslint/strict-boolean-expressions": "error"
  "@typescript-eslint/no-inferrable-types": "off"
