name: Static Code Check

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Setup Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: "Install dependencies"
        run: npm install
      - name: "Run linter"
        run: npm run lint
      - name: "Check format"
        run: npm run format-check
